---
# Общие параметры
overall:
  # Место для сброса отчетов об ошибках
  error_log: /tmp/parser.log
parser:
  log_file: logs/access.log
  # Путь к папке с шаблонами сервисов
  services_dir: default.conf/services
database:
  # Файл, куда будет писать база данных
  database_file: archive/access.sqlite3
aggregator:
  # Файл, из которого будет читать агрегатор
  database_file: archive/access.sqlite3
reporter:
  # Файл, в который будет выдан основной отчет
  report_file: report/report.html
  # Папка с настройками отображения отчета
  config_folder: default.conf/report